### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by rogerclarkmelbourne** [ZinderAsh/JavaScript-Pacman#1]
There is no license on these files, which AFIK means all rights reserved by the author

Please can you clarify if the code can be used and what conditions.

I'm not suggesting you license as GPL, as this actually prevents the code being used in a lot of situations.

Perhaps BSD, or Apache or MIT license?

**Comment by ZinderAsh** [comment]
I left this project here mainly for portfolio reasons, but adding a license is no big issue if that is desired.
Do you need this project for anything in particular?

**Comment by rogerclarkmelbourne** [comment]
Thanks.
I think I will probably use different JavaScript PacMan

https://github.com/mumuy/pacman

As it is MIT license

I need it for an educational / not for profit website I'm working for.

**Comment by ZinderAsh** [comment]
Ah, I see. I have added an MIT license anyway. Good luck with your project!

**Comment by rogerclarkmelbourne** [comment]
Thanks
